import JSZip from "jszip";
import type { PackingResult } from "./print-planner";

// ── Binary STL Writer ────────────────────────────────────────────────────────

interface MeshData {
  triVerts: Uint32Array;
  vertProperties: Float32Array;
  numProp: number;
}

/**
 * Convert a Manifold mesh to binary STL format.
 * Binary STL: 80-byte header, 4-byte triangle count, then 50 bytes per triangle
 * (12 bytes normal + 36 bytes vertices + 2 bytes attribute).
 */
export function meshToStlBinary(mesh: MeshData): ArrayBuffer {
  const { triVerts, vertProperties, numProp } = mesh;
  const triCount = triVerts.length / 3;
  const bufferSize = 80 + 4 + triCount * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // 80-byte header (zeros)
  // Already zeroed by ArrayBuffer constructor

  // Triangle count
  view.setUint32(80, triCount, true);

  let offset = 84;
  for (let t = 0; t < triCount; t++) {
    const i0 = triVerts[t * 3]!;
    const i1 = triVerts[t * 3 + 1]!;
    const i2 = triVerts[t * 3 + 2]!;

    // Vertex positions
    const ax = vertProperties[i0 * numProp]!;
    const ay = vertProperties[i0 * numProp + 1]!;
    const az = vertProperties[i0 * numProp + 2]!;
    const bx = vertProperties[i1 * numProp]!;
    const by = vertProperties[i1 * numProp + 1]!;
    const bz = vertProperties[i1 * numProp + 2]!;
    const cx = vertProperties[i2 * numProp]!;
    const cy = vertProperties[i2 * numProp + 1]!;
    const cz = vertProperties[i2 * numProp + 2]!;

    // Face normal (cross product of two edges)
    const e1x = bx - ax;
    const e1y = by - ay;
    const e1z = bz - az;
    const e2x = cx - ax;
    const e2y = cy - ay;
    const e2z = cz - az;
    let nx = e1y * e2z - e1z * e2y;
    let ny = e1z * e2x - e1x * e2z;
    let nz = e1x * e2y - e1y * e2x;
    const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
    if (len > 0) {
      nx /= len;
      ny /= len;
      nz /= len;
    }

    // Normal
    view.setFloat32(offset, nx, true);
    view.setFloat32(offset + 4, ny, true);
    view.setFloat32(offset + 8, nz, true);

    // Vertex 1
    view.setFloat32(offset + 12, ax, true);
    view.setFloat32(offset + 16, ay, true);
    view.setFloat32(offset + 20, az, true);

    // Vertex 2
    view.setFloat32(offset + 24, bx, true);
    view.setFloat32(offset + 28, by, true);
    view.setFloat32(offset + 32, bz, true);

    // Vertex 3
    view.setFloat32(offset + 36, cx, true);
    view.setFloat32(offset + 40, cy, true);
    view.setFloat32(offset + 44, cz, true);

    // Attribute byte count (unused, set to 0)
    view.setUint16(offset + 48, 0, true);

    offset += 50;
  }

  return buffer;
}

// ── ZIP Bundle ───────────────────────────────────────────────────────────────

/**
 * Create a ZIP file containing STL files and a print plan.
 * Returns a Blob ready for download.
 */
export async function createExportZip(
  stlFiles: { name: string; data: ArrayBuffer }[],
  printPlan: string
): Promise<Blob> {
  const zip = new JSZip();

  for (const file of stlFiles) {
    zip.file(file.name, file.data);
  }

  zip.file("print-plan.md", printPlan);

  return zip.generateAsync({ type: "blob" });
}

// ── Print Plan Markdown ──────────────────────────────────────────────────────

export function generatePrintPlanMarkdown(result: PackingResult): string {
  const lines: string[] = [];

  lines.push("# Print Plan");
  lines.push("");
  lines.push(
    `**Total: ${result.totalSheets} sheet${result.totalSheets !== 1 ? "s" : ""}**`
  );
  lines.push("");

  // Inventory
  lines.push("## Parts Inventory");
  lines.push("");
  lines.push("| Part | Qty | Size (mm) |");
  lines.push("|------|-----|-----------|");
  for (const entry of result.inventory) {
    lines.push(
      `| ${entry.label} | ×${entry.quantity} | ${entry.width} × ${entry.length} |`
    );
  }
  lines.push("");

  // Per-sheet details
  lines.push("## Print Sheets");
  lines.push("");
  for (const sheet of result.sheets) {
    lines.push(
      `### Sheet ${sheet.index + 1} (${sheet.placements.length} part${sheet.placements.length !== 1 ? "s" : ""})`
    );
    lines.push("");
    for (const p of sheet.placements) {
      lines.push(
        `- [ ] ${p.item.label} at (${p.x.toFixed(1)}, ${p.y.toFixed(1)})`
      );
    }
    lines.push("");
  }

  // Unpacked warnings
  if (result.unpacked.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    for (const item of result.unpacked) {
      lines.push(
        `- **${item.label}** (${item.width}×${item.length}mm) — too large for print bed`
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Tessera*");

  return lines.join("\n");
}

// ── Browser Download Helper ──────────────────────────────────────────────────

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
